# Ex057 - Exception handling (3): try~except~finally

try:
    print('Hello.')
    print(param)
except:
    print('Exception has occurred!')
finally:
    print('This section is always executed')
